# Generated by Django 5.2.8 on 2026-01-12 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория функций',
                'verbose_name_plural': 'категории функций',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KriteriiInvalid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'критерий инвалидности',
                'verbose_name_plural': 'критерии инвалидности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepenFuncii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stenen', models.PositiveSmallIntegerField(help_text='0 = нарушение отсутствует, 6 = полное нарушение', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='степень выраженности нарушения')),
                ('title', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'степень выраженности нарушения',
                'verbose_name_plural': 'степени выраженности нарушений',
                'ordering': ['stenen'],
            },
        ),
        migrations.CreateModel(
            name='FunciaVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='код')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='вид', to='krit_invalid.funcia', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'вид функции',
                'verbose_name_plural': 'виды функций',
                'ordering': ['category', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FuncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='krit_invalid.kriteriiinvalid', verbose_name='пациент')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='func_statuses', to='krit_invalid.stepenfuncii', verbose_name='функция')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='severity_statuses', to='krit_invalid.stepenfuncii', verbose_name='степень')),
            ],
            options={
                'verbose_name': 'статус функции',
                'verbose_name_plural': 'статусы функций',
                'unique_together': {('patient', 'func')},
            },
        ),
    ]
