# Generated by Django 5.2.8 on 2026-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFormM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=100)),
                ('passward', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterFormM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(db_index=True, max_length=100, unique=True)),
                ('passward1', models.CharField(max_length=100)),
                ('passward2', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, help_text='Необязательно. JPG/PNG, max 2 МБ', null=True, upload_to='avatars/%Y/%m/')),
            ],
        ),
    ]
