# Generated by Django 5.2.8 on 2025-12-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiz_razv', '0009_delete_osmotrpatient_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data_birth', models.DateField()),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('rost', models.FloatField()),
                ('ves', models.FloatField()),
                ('imt', models.FloatField(editable=False)),
                ('foto', models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/', width_field='width')),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OsmotrPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_osmotra', models.DateTimeField(auto_now_add=True)),
                ('rost_centil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('rost_SDS', models.FloatField()),
                ('ves_centil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('ves_SDS', models.FloatField()),
                ('imt_centil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('imt_SDS', models.FloatField()),
                ('fizic_razvitie', models.ManyToManyField(to='fiz_razv.fizicrazvit')),
                ('narushenie', models.ManyToManyField(to='fiz_razv.narushenie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
