# Generated by Django 5.2.8 on 2026-01-09 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiz_razv', '0010_alter_fizicrazvit_type_razvitya'),
        ('mkb10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('data_birth', models.DateField(db_index=True)),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], db_index=True, max_length=1)),
                ('diagnoz_osn', models.CharField(blank=True, max_length=1000, null=True)),
                ('diagnoz_sop', models.CharField(blank=True, max_length=1000, null=True)),
                ('suz', models.IntegerField(blank=True, null=True)),
                ('rost', models.FloatField(blank=True, null=True)),
                ('ves', models.FloatField(blank=True, null=True)),
                ('imt', models.FloatField(blank=True, editable=False, null=True)),
                ('foto', models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/%Y/%m/', width_field='width')),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('mkb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mkb10.mkb10')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OsmotrPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_osmotra', models.DateField(default=django.utils.timezone.localdate)),
                ('diagnoz_osn', models.CharField(blank=True, max_length=1000, null=True)),
                ('diagnoz_sop', models.CharField(blank=True, max_length=1000, null=True)),
                ('suz', models.IntegerField(blank=True, null=True)),
                ('rp', models.CharField(blank=True, choices=[('В', 'высокий'), ('С', 'средний'), ('Н', 'низкий'), ('КН', 'крайне низкий'), ('О', 'отсутствует')], max_length=15, null=True)),
                ('rost', models.FloatField(blank=True, null=True)),
                ('ves', models.FloatField(blank=True, null=True)),
                ('imt', models.FloatField(blank=True, editable=False, null=True)),
                ('rost_centil', models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True)),
                ('rost_SDS', models.FloatField(blank=True, editable=False, null=True)),
                ('ves_centil', models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True)),
                ('ves_SDS', models.FloatField(blank=True, editable=False, null=True)),
                ('imt_centil', models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True)),
                ('imt_SDS', models.FloatField(blank=True, editable=False, null=True)),
                ('fizic_razvitie', models.ManyToManyField(editable=False, to='fiz_razv.fizicrazvit')),
                ('narushenie', models.ManyToManyField(editable=False, to='fiz_razv.narushenie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osmotrs', to='patient.patient')),
            ],
            options={
                'ordering': ['-data_osmotra'],
            },
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='patient_image/%Y/%m/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
