# Generated by Django 5.2.8 on 2025-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0009_delete_osmotrpatient_delete_patient'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmotrpatient',
            name='imt',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='osmotrpatient',
            name='rost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osmotrpatient',
            name='ves',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='fizic_razvitie',
            field=models.ManyToManyField(editable=False, to='fiz_razv.fizicrazvit'),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='imt_SDS',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='imt_centil',
            field=models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='narushenie',
            field=models.ManyToManyField(editable=False, to='fiz_razv.narushenie'),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='rost_SDS',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='rost_centil',
            field=models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='ves_SDS',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='ves_centil',
            field=models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10),
        ),
    ]
