# Generated by Django 5.2.8 on 2025-12-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_osmotrpatient_imt_osmotrpatient_rost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmotrpatient',
            name='imt_SDS',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='imt_centil',
            field=models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='rost_SDS',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='rost_centil',
            field=models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='ves_SDS',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='osmotrpatient',
            name='ves_centil',
            field=models.CharField(blank=True, choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], editable=False, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tovar_image')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
