# Generated by Django 5.2.8 on 2025-12-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_osmotrpatient_imt_sds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientimage',
            old_name='tovar',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='img',
            field=models.ImageField(upload_to='patient_image'),
        ),
    ]
