# Generated by Django 5.2.8 on 2026-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MKB10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код диагноза по МКБ-10')),
                ('name', models.TextField(verbose_name='Диагноза по МКБ-10')),
                ('parent', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код родителя')),
            ],
            options={
                'verbose_name': 'МКБ-10',
                'verbose_name_plural': 'МКБ-10',
                'ordering': ['code'],
            },
        ),
    ]
