# Generated by Django 5.2.8 on 2025-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('age', models.FloatField()),
                ('ME', models.FloatField()),
                ('SD', models.FloatField()),
                ('p3', models.FloatField()),
                ('p10', models.FloatField()),
                ('p25', models.FloatField()),
                ('p50', models.FloatField()),
                ('p75', models.FloatField()),
                ('p90', models.FloatField()),
                ('p97', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('age', models.FloatField()),
                ('ME', models.FloatField()),
                ('SD', models.FloatField()),
                ('p3', models.FloatField()),
                ('p10', models.FloatField()),
                ('p25', models.FloatField()),
                ('p50', models.FloatField()),
                ('p75', models.FloatField()),
                ('p90', models.FloatField()),
                ('p97', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('age', models.FloatField()),
                ('ME', models.FloatField()),
                ('SD', models.FloatField()),
                ('p3', models.FloatField()),
                ('p10', models.FloatField()),
                ('p25', models.FloatField()),
                ('p50', models.FloatField()),
                ('p75', models.FloatField()),
                ('p90', models.FloatField()),
                ('p97', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
