# Generated by Django 5.2.8 on 2025-11-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0002_imt_rost_ves'),
    ]

    operations = [
        migrations.AddField(
            model_name='imt',
            name='age_int1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imt',
            name='age_int2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rost',
            name='age_int1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rost',
            name='age_int2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ves',
            name='age_int1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ves',
            name='age_int2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
