# Generated by Django 5.2.8 on 2025-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0003_imt_age_int1_imt_age_int2_rost_age_int1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imt',
            name='age_int1',
        ),
        migrations.RemoveField(
            model_name='imt',
            name='age_int2',
        ),
        migrations.RemoveField(
            model_name='rost',
            name='age_int1',
        ),
        migrations.RemoveField(
            model_name='rost',
            name='age_int2',
        ),
        migrations.RemoveField(
            model_name='ves',
            name='age_int1',
        ),
        migrations.RemoveField(
            model_name='ves',
            name='age_int2',
        ),
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/', width_field='width'),
        ),
    ]
