# Generated by Django 5.2.8 on 2025-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0004_remove_imt_age_int1_remove_imt_age_int2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height_f',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='width_f',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
