# Generated by Django 5.2.8 on 2025-11-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0005_patient_height_f_patient_width_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='height_f',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='width_f',
            new_name='width',
        ),
    ]
