# Generated by Django 5.2.8 on 2025-12-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0006_rename_height_f_patient_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FizicRazvit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_razvitya', models.CharField(choices=[('высокое', 'Физическое развитие высокое'), ('выше среднего', 'Физическое развитие выше среднего'), ('ниже среднего', 'Физическое развитие ниже среднего'), ('низкое', 'Физическое развитие низкое'), ('очень высокое', 'Физическое развитие очень высокое'), ('очень низкое', 'Физическое развитие очень низкое'), ('без определенного вариант', 'Физическое развитие без определенного вариант'), ('среднее', 'Физическое развитие среднее')], max_length=100)),
                ('type_garmonic', models.CharField(choices=[('гарм', 'гармоничное'), ('дисгарм', 'дисгармоничное'), ('резкодис', 'резко дисгармоничное')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Narushenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_narushenia', models.CharField(choices=[('ХБЭН', 'Низкорослость или хроническая белково-энергетическая недостаточность, умеренной степени'), ('Выс', 'Высокорослость'), ('Ожир', 'Ожирение'), ('ИМТ', 'Избыток массы тела'), ('ОБЭН3', 'Острая белково-энергетическая недостаточность, тяжёлой степени'), ('ОБЭН2', 'Острая белково-энергетическая недостаточность, умеренной степени'), ('Нарушений не выявлено', 'Нарушений не выявлено')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OsmotrPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_osmotra', models.DateTimeField(auto_now_add=True)),
                ('rost_centil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('rost_SDS', models.FloatField()),
                ('ves_сentil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('ves_SDS', models.FloatField()),
                ('imt_сentil', models.CharField(choices=[('ниже 3', 'ниже 3'), ('3-10', '3-10'), ('10-25', '10-25'), ('25-75', '25-75'), ('75-90', '75-90'), ('90-97', '90-97'), ('выше 97', 'выше 97')], max_length=10)),
                ('imt_SDS', models.FloatField()),
                ('fizic_razvitie', models.ManyToManyField(to='fiz_razv.fizicrazvit')),
                ('narushenie', models.ManyToManyField(to='fiz_razv.narushenie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiz_razv.patient')),
            ],
        ),
    ]
