# Generated by Django 5.2.8 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0007_fizicrazvit_narushenie_osmotrpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='width',
        ),
        migrations.AlterField(
            model_name='fizicrazvit',
            name='type_garmonic',
            field=models.CharField(choices=[('Г', 'гармоничное'), ('ДГ', 'дисгармоничное'), ('РДГ', 'резко дисгармоничное')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fizicrazvit',
            name='type_razvitya',
            field=models.CharField(choices=[('В', 'высокое'), ('ВС', 'выше среднего'), ('НС', 'ниже среднего'), ('Н', 'низкое'), ('ОВ', 'очень высокое'), ('ОН', 'очень низкое'), ('БОВ', 'без определенного вариант'), ('С', 'среднее')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='imt',
            field=models.FloatField(editable=False),
        ),
    ]
