# Generated by Django 5.2.8 on 2025-12-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0008_remove_patient_height_remove_patient_width_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsmotrPatient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
