# Generated by Django 5.2.8 on 2025-12-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz_razv', '0009_delete_osmotrpatient_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizicrazvit',
            name='type_razvitya',
            field=models.CharField(choices=[('В', 'высокое'), ('ВС', 'выше среднего'), ('НС', 'ниже среднего'), ('Н', 'низкое'), ('ОВ', 'очень высокое'), ('ОН', 'очень низкое'), ('БОВ', 'без определенного варианта'), ('С', 'среднее')], max_length=30),
        ),
    ]
